# Generated by Django 5.0.6 on 2024-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_de_l_exercice', models.CharField(max_length=200)),
                ('type_d_exercice', models.CharField(max_length=200)),
                ('partie_de_corps_ciblée', models.CharField(max_length=200)),
                ('niveau', models.IntegerField()),
                ('description', models.TextField()),
                ('illustration', models.URLField()),
            ],
        ),
    ]
