# Generated by Django 5.0.6 on 2024-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='illustration',
            field=models.CharField(max_length=200),
        ),
    ]
